#!/usr/bin/env bash

# SPDX-License-Identifier: GPL-2.0-or-later
# https://github.com/dehesselle/giru

### description ################################################################

# Provide initscript-style service for gitlab-runner on macOS.
# Requires the following environment variables to operate:
#    HOMEBREW_PREFIX       to find gitlab-runner binary

### includes ###################################################################

INCLUDE_DIR=$(dirname $0)/bash_d
source $INCLUDE_DIR/1_include_.sh
include_file daemon_.sh
include_file echo_.sh
include_file str_.sh
include_file xdg_.sh

### variables ##################################################################

RUNNER=$HOMEBREW_PREFIX/bin/gitlab-runner
RUNNER_CONFIG_DIR=$(xdg_get_config_home)/gitlab-runner
RUNNER_CONFIG_FILE=

DAEMON_NAME=gitlab-runner
DAEMON_SHUTDOWN_GRACE=60   # gitlab-runner takes its time to shutdown gracefully

### functions ##################################################################

function daemon_print_usage
{
  echo_i "usage: $0 {service} {start|stop|restart|status}"
}

function daemon_run
{
  local log_dir=$(grep builds_dir $RUNNER_CONFIG_FILE | awk '{ print $3 }')
  log_dir="${log_dir%\"}"
  log_dir="${log_dir#\"}"

  if $(str_is_empty $log_dir); then
    log_dir=$(xdg_get_cache_home)
    mkdir -p $log_dir
  else
    if [ ! -d $log_dir ]; then
      echo_e "not a directory: log_dir = $log_dir"
      exit 1
    fi
  fi

  local service=$(basename -s .toml $RUNNER_CONFIG_FILE)

  $RUNNER run \
    --config $RUNNER_CONFIG_FILE \
    --service $service \
    1>> $log_dir/${service}_stdout.log \
    2>> $log_dir/${service}_stderr.log \
    &

  echo $! > $DAEMON_PIDFILE
}

function main
{
  local service=$1
  local command=$2

  if [ $# -eq 2 ]; then
    RUNNER_CONFIG_FILE=$RUNNER_CONFIG_DIR/$service.toml
    DAEMON_PIDFILE=$(xdg_get_runtime_dir)/$service.pid

    if [ -f $RUNNER_CONFIG_FILE ]; then
      daemon_dispatch $command
    else
      echo_e "unknown service $service"
    fi
  else
    daemon_print_usage
    exit 1
  fi
}

### aliases ####################################################################

# Nothing here.

### main #######################################################################

main $*
